# Generated by Django 4.1.5 on 2023-01-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
