# Generated by Django 4.1.5 on 2023-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='images/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='/media/default.jpg', upload_to='images/%Y-%m-%d/'),
        ),
    ]
